version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:80"
    environment:
      - APP_ENV=development
      - APP_DEBUG=true
      - APP_URL=http://localhost:8000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=construction_saas
      - DB_USER=postgres
      - DB_PASSWORD=password
      - SESSION_SECRET=dev-secret-key
      - ENCRYPTION_KEY=dev-encryption-key
    depends_on:
      - db
    volumes:
      - ./public/uploads:/var/www/html/public/uploads
    networks:
      - construction-network

  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=construction_saas
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/sample_data.sql:/docker-entrypoint-initdb.d/02-sample-data.sql
    networks:
      - construction-network

volumes:
  postgres_data:

networks:
  construction-network:
    driver: bridge